---
kind: pipeline
type: docker
name: build

steps:
  - name: lint
    image: golangci/golangci-lint:v1.43.0
    environment:
      CGO_ENABLED: 0
    commands:
      - golangci-lint run

  - name: test
    image: golang:1.17.3-alpine
    environment:
      CGO_ENABLED: 0
    commands:
      - go test ./...

  - name: docker
    image: plugins/docker
    when:
      branch: master
    settings:
      username:
        from_secret: dockerhub_user
      password:
        from_secret: dockerhub_password
      repo: pztrn/fastpastebin
      auto_tag: true
