run:
  deadline: 5m
linters:
  enable-all: true
  disable:
    # Because globals might exist, but according to our codestyle they
    # should be lowercased and considered as unexported.
    - gochecknoglobals
    # While it might be useful it'll create more problems that will solve.
    - gocritic
    # Complains about main() lengths, which isn't an issue.
    - funlen
    # Magic numbers everywhere and we can't get rid of them.
    - gomnd
    # This linter MIGHT BE good, but who decided that I want keepFor in
    # JSON instead of keep_for for KeepFor field?
    - tagliatelle
    # Why it is bad to return an interface? No one knows, except authors of this linter.
    - ireturn
    # Some structs will contain context, and it's cancelFunc.
    - containedctx
    # Deprecated.
    - exhaustivestruct
    - golint
    - wrapcheck
linters-settings:
  lll:
    line-length: 420
  gocognit:
    min-complexity: 50
  gocyclo:
    min-complexity: 40
  cyclop:
    max-complexity: 40

issues:
  exclude-rules:
    # There will be some ToDos.
    - linters:
        - godox
      text: "TODO"
